version: 2
jobs:
  terraform:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: lint-validate
          command: |
            chmod +x .circleci/lint.sh
            chmod +x .circleci/validate.sh
            source .circleci/lint.sh
            source .circleci/validate.sh
  bump:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: install semver
          command: |
            /usr/bin/python3 -m pip install -r requirements.txt
      - run:
          name: bump version
          command: |
            chmod +x .circleci/bump.sh
            source .circleci/bump.sh

workflows:
  version: 2
  build:
    jobs:
      - terraform:
          context: terraform
      - bump:
          context: terraform
          filters:
            branches:
              only: master
  